# create database with name ecommerce_project
CREATE DATABASE ecommerce_project;

# use the database ecommerce_project
USE ecommerce_project;

# import table data - customers, orders, order_items, products, payments, sellers using local address of csv files

# Key Metrics
# 1.Total customers
select count(distinct customer_id) as total_customers from customers;
# 2.Total orders
select count(distinct order_id) as total_orders from orders;
# 3.Total sellers
select count(distinct seller_id) as total_sellers from sellers;
# 4.Total revenue
select round(sum(price + freight_value),0) as total_revenue from order_items;


# Basic Problems
# Objective : Extract fundamental insights from the dataset. 


# Q1: List all unique cities where customers located.
select distinct customer_city from customers;



# Q2: Count the number of orders placed in 2017.
select count(*) from orders 
where left(order_purchase_timestamp,4)=2017;



# Q3: Find the total sales per category.
select distinct p.product_category, 
round(SUM(oi.price + oi.freight_value),2) as total_sales 
from order_items oi 
join products p on oi.product_id = p.product_id 
group by p.product_category
order by total_sales desc;



# Q4: Calculate the percentage of orders that were paid in installments.
select round((count(case
                   when payment_installments > 1
				   then order_id
			  end)
/
count(distinct order_id))*100,2) as installment_percentage 
from payments;



# Q5: Count the number customers from each state.
select customer_state, count(*) as no_customers 
from customers
group by customer_state
order by no_customers desc;



# Intermediate Problems:
# Objective: Dive deeper into sales and order trends

# Q1: Calculate the number of orders in 2018.
select date_format(order_purchase_timestamp, '%Y-%m') as month,
count(order_id) as total_orders from orders 
where YEAR(order_purchase_timestamp)=2018
group by month
order by month;



# Q2: Find the average number of products per order, grouped by customer city
select c.customer_city, 
round(AVG(product_count),0) as avg_products_per_order 
from 
(select o.order_id, o.customer_id, count(oi.product_id) as product_count 
from orders o 
join order_items oi 
on o.order_id = oi.order_id
group by o.order_id, o.customer_id) as order_products_counts 
join customers c on order_products_counts.customer_id = c.customer_id
group by c.customer_city 
order by avg_products_per_order desc; 



# Q3: Calculate the percentage of total revenue contributed by each product category.
select p.product_category, 
round(sum(oi.price + oi.freight_value)*100 / t.total_revenue,2) as revenue_percentage
from order_items oi 
join products p on oi.product_id = p.product_id 
cross join (select sum(price + freight_value) as total_revenue
from order_items)t
group by p.product_category, t.total_revenue
order by revenue_percentage desc;



# Q4: Identify the correlation between the price and the number of times a product has been purchased.
select round((count(*) * sum(avg_price * purchase_count) - sum(avg_price) * sum(purchase_count))
/
sqrt((count(*) * sum(power(avg_price,2)) - power(sum(avg_price),2)) * (count(*) *  
sum(power(purchase_count,2)) - power(sum(purchase_count),2))),2) as correlation
from (select product_id, avg(price) as avg_price, count(*) as purchase_count 
from order_items group by product_id) as product_stats;



# Q5: Calculate the total revenue generated by each seller, and rank them by revenue.
select seller_id, round(sum(price + freight_value),2) as total_revenue, 
rank() over (order by sum(price + freight_value) desc) as revenue_rank
from order_items
group by seller_id
order by total_revenue desc;



# Advanced Problems:
# Objective: Generate strategic and customer-centric insights. 

# Q1: Calculate the moving average of order values for each customer over their order history. 
select o.customer_id, o.order_id, o.order_purchase_timestamp, p.payment_value as order_value,
avg(p.payment_value) over (partition by o.customer_id order by o.order_purchase_timestamp
rows between 2 preceding and current row) as moving_avg_order_value
from orders o join payments p 
on o.order_id = p.order_id
order by o.customer_id, o.order_purchase_timestamp ;



# Q2: Calculate the cumulative sales for per month for each year.
select year(order_purchase_timestamp) as year, 
month(order_purchase_timestamp) as month,
sum(payment_value) as monthly_sales, 
sum(sum(payment_value)) over (partition by year(order_purchase_timestamp)
order by month(order_purchase_timestamp)) as cumulative_sales
from orders o 
join payments p on o.order_id = p.order_id
group by year(order_purchase_timestamp), month(order_purchase_timestamp)
order by year, month;



# Q3: Calculate the year-over-year growth rate of total sales.
select year, total_sales,
lag(total_sales) over (order by year) as previous_year_sales,
round((total_sales - lag(total_sales) over (order by year))
/
lag(total_sales) over (order by year) * 100,2) as yoy_growth_percentage
from (select year(o.order_purchase_timestamp) as year, 
round(sum(p.payment_value),2) as total_sales from orders o join payments p on o.order_id = p.order_id
group by year(o.order_purchase_timestamp)) as yearly_sales
order by year;



# Q4: Calculate the retention rate of customers 
#     defined as the percentage of customers who make another purchase within 6 months of their first purchase
SELECT 
    ROUND(
        COUNT(DISTINCT r.customer_unique_id) * 100.0 /
        COUNT(DISTINCT f.customer_unique_id),
    2) AS retention_rate_percentage
FROM first_purchase f
LEFT JOIN repeat_purchase r ON f.customer_unique_id = r.customer_unique_id;
  
  
  
# Q5: Identify the top 3 customers who spent the most money in each year.
SELECT year, customer_id, total_spent
FROM (
    SELECT YEAR(o.order_purchase_timestamp) AS year, c.customer_id,
        SUM(oi.price + oi.freight_value) AS total_spent,
        DENSE_RANK() OVER (
            PARTITION BY YEAR(o.order_purchase_timestamp)
            ORDER BY SUM(oi.price + oi.freight_value) DESC
        ) AS rank_position
    FROM orders o
    JOIN customers c 
        ON o.customer_id = c.customer_id
    JOIN order_items oi 
        ON o.order_id = oi.order_id
    GROUP BY year, c.customer_id
) ranked_data
WHERE rank_position <= 3
ORDER BY year, total_spent DESC;
